### ISSUE TITLE
jsonnet gem fails to compile on ruby-builder:3.3.3.

### ISSUE THREAD

**Issue by sengi** [alphagov/govuk-ruby-images#96]
g++ complains about a missing header.

```
27.04 cpp/libjsonnet++.cpp:66:27: error: 'uint32_t' was not declared in this scope
27.04    66 | void Jsonnet::setMaxTrace(uint32_t lines)
27.04       |                           ^~~~~~~~
27.04 cpp/libjsonnet++.cpp:66:27: note: 'uint32_t' is defined in header '<cstdint>';
27.04 did you forget to '#include <cstdint>'?
```

This breaks the alphagov/publishing-api build ([example](https://github.com/alphagov/publishing-api/actions/runs/9676417292)).

Kudos to @Gweaton for reporting this.

**Comment by sengi** [comment]
Looks like it really is just a missing include in jsonnet, already fixed in 2022: https://www.github.com/google/jsonnet/commit/e43ca8e.

So not a bug in govuk-ruby-images.

Frustratingly, https://github.com/yugui/ruby-jsonnet pins v0.18.0 of libjsonnet++ and ruby-jsonnet's last update was 2 years ago.

Let's see if we can work around that by setting [JSONNET_USE_SYSTEM_LIBRARIES](https://github.com/yugui/ruby-jsonnet/blob/e8c4469/ext/jsonnet/extconf.rb#L5).

**Comment by sengi** [comment]
ruby-jsonnet bug worked around in #97 + alphagov/publishing-api#2788. Having the libjsonnet version under our control is a small win as it'll be kept up-to-date by default now that we're using the Ubuntu package.
